#!/bin/bash

# Quick Help Script
# Shows the main commands and setup

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "╔════════════════════════════════════════════════════════════╗"
echo "║      Lightning Custodial Wallet - Hackathon Setup          ║"
echo "║                    QUICK HELP                              ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

echo "📍 Project Location: $PROJECT_DIR"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 Quick Start (First Time Setup)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Setup everything:"
echo "   cd $PROJECT_DIR"
echo "   ./scripts/setup.sh"
echo ""
echo "2. Extract LND credentials (from Polar):"
echo "   ./scripts/extract_lnd_credentials.sh Lightning-Test-Network lnd_alice"
echo ""
echo "3. Configure Lightning API .env:"
echo "   nano backends/lightning-api/.env"
echo "   (Paste credentials from step 2)"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🏃 Running the Backends"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Terminal 1 - Lightning API:"
echo "   cd $PROJECT_DIR"
echo "   ./scripts/start.sh lightning"
echo ""
echo "Terminal 2 - User Backend:"
echo "   cd $PROJECT_DIR"
echo "   ./scripts/start.sh user"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🧪 Testing"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Run complete test (after both backends are running):"
echo "   cd $PROJECT_DIR"
echo "   ./scripts/test_lightning_complete.sh"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📚 Documentation"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Main Documents:"
echo "  guides/README_LIGHTNING_TESTING.md      - Overview"
echo "  guides/LIGHTNING_QUICK_CHECKLIST.md     - Step-by-step"
echo "  guides/GUIDE_LIGHTNING_TESTING.md       - Detailed reference"
echo ""
echo "Config Files:"
echo "  config/.env.lightning.example           - Lightning API template"
echo "  config/.env.user.example                - User Backend template"
echo ""
echo "Actual Config Files (create after setup.sh):"
echo "  backends/lightning-api/.env"
echo "  backends/user-backend/.env"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 Project Structure"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "$PROJECT_DIR/"
echo "├── backends/              # Both backends"
echo "│   ├── lightning-api/    # Lightning Network API (port 5003)"
echo "│   └── user-backend/     # User Backend (port 7000)"
echo "├── scripts/               # Automation scripts"
echo "│   ├── setup.sh          # Initial setup"
echo "│   ├── start.sh          # Start backends"
echo "│   ├── extract_lnd_credentials.sh"
echo "│   └── test_lightning_complete.sh"
echo "├── config/                # Configuration templates"
echo "│   ├── .env.lightning.example"
echo "│   └── .env.user.example"
echo "├── guides/                # Documentation"
echo "│   ├── README_LIGHTNING_TESTING.md"
echo "│   ├── LIGHTNING_QUICK_CHECKLIST.md"
echo "│   └── GUIDE_LIGHTNING_TESTING.md"
echo "└── docs/                  # Additional docs"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔗 API Endpoints"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Lightning API (Port 5003):"
echo "  - POST   /api/invoice        - Create invoice"
echo "  - POST   /api/pay            - Pay invoice"
echo "  - GET    /api/invoices       - List invoices"
echo "  - GET    /api/getinfo        - Node info"
echo "  - GET    /api/balance        - Node balance"
echo ""
echo "User Backend (Port 7000):"
echo "  - POST   /api/register       - Register user"
echo "  - POST   /api/login          - Login"
echo "  - GET    /api/me             - User info"
echo "  - POST   /api/request-payment   - Create invoice"
echo "  - GET    /api/check-payment/:id - Check payment"
echo "  - POST   /api/send-payment   - Send payment"
echo "  - POST   /api/transfer       - Transfer sats"
echo "  - GET    /api/history        - Transaction history"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✨ Ready for Hackathon! 🚀"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
